In [141]:
import pandas as pd

In [145]:
df= pd.read_csv("data.csv")

In [147]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 12 non-null     object
 1   Film                  12 non-null     object
 2   Year                  12 non-null     int64
 3   Genre                 12 non-null     object
 4   BoxOffice(INR Crore)  12 non-null     int64
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes

In [151]:
df.describe()

              Year  BoxOffice(INR Crore)       IMDb
count    12.000000             12.000000  12.000000
mean   2019.000000            545.666667   6.975000
std       2.215647            528.535942   0.981766
min    2016.000000            111.000000   5.600000
25%    2017.750000            249.750000   6.075000
50%    2018.500000            386.500000   7.000000
75%    2019.750000            570.000000   7.675000
max    2023.000000           2024.000000   8.400000

In [155]:
df.shape

(12, 6)

In [167]:
df.isnull().sum()

Actor                   0
Film                    0
Year                    0
Genre                   0
BoxOffice(INR Crore)    0
IMDb                    0
dtype: int64

In [169]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [173]:
df.sort_values('Year', ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [186]:
df2 = df['Year'] > 2020

In [188]:
df[df2]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [195]:
df[df['Genre'] == 'Action']

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [197]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [260]:
df['avg_IMDb'] = df.groupby('Actor')['IMDb'].transform('mean')

In [262]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,avg_IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,8.2

In [276]:
df['IMDb'].mean()

6.9750000000000005

In [278]:
df.groupby('Actor')['BoxOffice(INR Crore)'].max()

Actor
Aamir Khan            2024
Akshay Kumar           318
Ayushmann Khurrana     111
Hrithik Roshan         475
Kartik Aaryan          266
Rajkummar Rao          180
Ranbir Kapoor          431
Ranveer Singh          585
Salman Khan            565
Shah Rukh Khan        1050
Varun Dhawan           201
Vicky Kaushal          342
Name: BoxOffice(INR Crore), dtype: int64

In [314]:
df2 = df[['Film','IMDb']]

In [316]:
df2

                        Film  IMDb
0                    Pathaan   7.2
1            Tiger Zinda Hai   6.0
2                     Dangal   8.4
3                 Brahmastra   5.6
4                  Padmaavat   7.0
5                  Andhadhun   8.3
6                      Stree   7.5
7                        War   6.5
8                 Good Newwz   7.0
9          Bhool Bhulaiyaa 2   5.9
10     Badrinath Ki Dulhania   6.1
11  Uri: The Surgical Strike   8.2

In [318]:
df2[df2['IMDb'] > 7]

                        Film  IMDb
0                    Pathaan   7.2
2                     Dangal   8.4
5                  Andhadhun   8.3
6                      Stree   7.5
11  Uri: The Surgical Strike   8.2

In [328]:
df[df['Genre'] == 'Action']['Film'].count()

4

In [330]:
df['BoxOffice(INR Crore)'].sum()

6548

In [340]:
df.groupby('Film')['IMDb'].min()

Film
Andhadhun                   8.3
Badrinath Ki Dulhania       6.1
Bhool Bhulaiyaa 2           5.9
Brahmastra                  5.6
Dangal                      8.4
Good Newwz                  7.0
Padmaavat                   7.0
Pathaan                     7.2
Stree                       7.5
Tiger Zinda Hai             6.0
Uri: The Surgical Strike    8.2
War                         6.5
Name: IMDb, dtype: float64

In [350]:
df[df['Year'] > 2018].shape[0]

6

In [352]:
df.sort_values('IMDb', ascending=False).head(5)[['Film', 'IMDb']]

                        Film  IMDb
2                     Dangal   8.4
5                  Andhadhun   8.3
11  Uri: The Surgical Strike   8.2
6                      Stree   7.5
0                    Pathaan   7.2

In [354]:
df[df['BoxOffice(INR Crore)'] == df['BoxOffice(INR Crore)'].max()][['Actor', 'Film']]

        Actor    Film
2  Aamir Khan  Dangal

In [356]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,avg_IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,8.2

In [360]:
df[df['IMDb'] == df['IMDb'].min()][['Actor','Film']]

           Actor        Film
3  Ranbir Kapoor  Brahmastra

In [364]:
df[df['Genre'] == "Horror Comedy"].shape[0]

2

In [370]:
df[df['BoxOffice(INR Crore)'] > 500].shape[0]

4

In [378]:
df[df['Year'] > 2018]['IMDb'].mean()

6.733333333333334

In [402]:
df[df['']]

Actor
Aamir Khan            8.4
Akshay Kumar          7.0
Ayushmann Khurrana    8.3
Hrithik Roshan        6.5
Kartik Aaryan         5.9
Rajkummar Rao         7.5
Ranbir Kapoor         5.6
Ranveer Singh         7.0
Salman Khan           6.0
Shah Rukh Khan        7.2
Varun Dhawan          6.1
Vicky Kaushal         8.2
Name: IMDb, dtype: float64